spring:
  jpa:
    database: mysql
    show-sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: update
  freemarker:
    cache: false
  datasource:
    hikari:
      driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
      jdbc-url: jdbc:log4jdbc:mysql://localhost:3306/management?useSSL=false&useUnicode=true&characterEncoding=utf8
      username: root
      password: test1234
      connection-test-query: SELECT NOW() FROM dual
  h2:
    console:
      enabled: true
  devtools:
    livereload:
      enabled: true
server:
  port: 8080
mybatis:
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    org.springframework.web: debug

graphql:
  servlet:
    mapping: /graphql
    enabled: true
    corsEnabled: true
  spqr:
    gui:
      enabled: true
  playground:
    cdn:
      enabled: true
    endpoint: /graphql

#cloud:
#  aws:
#    credentials:
#      access-key:
#      secret-key:
#    region:
#      static: ap-northeast-2
#    stack:
#      auto: false
