spring:
  jpa:
    database: mysql
    show-sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: update
  datasource:
    hikari:
      driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
      jdbc-url: jdbc:log4jdbc:mysql://localhost:3306/mydb?useSSL=false&useUnicode=true&characterEncoding=utf8
      username: root
      password: test1234
      connection-test-query: SELECT NOW() FROM dual
  h2:
    console:
      enabled: true
  devtools:
    livereload:
      enabled: true
server:
  port: 8080
mybatis:
  configuration:
    map-underscore-to-camel-case: true